### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hulkhawk** [Howchoo/dash-reboot#1]
tried to install this module for reseting my retropie system on raspberry pi, but always get the error:
"Error: Cannot find module 'node-dash-button'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/node_modules/node-dash-button/dash-reboot.js:1:81)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
"

Tried google-fu, but failed to find how to correct it. Could you please help me?

Thanks!

**Comment by jesmith0** [comment]
What command are you using to run the dash-reboot script?
